/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

/**
 *
 * @author roni9
 */
public class Cabecera_Compra extends javax.swing.JFrame {

    /**
     * Creates new form Cabecera_Compra
     */
    public Cabecera_Compra() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BT_Salir = new javax.swing.JButton();
        titulo = new javax.swing.JLabel();
        icono = new javax.swing.JLabel();
        Id = new javax.swing.JLabel();
        Fecha = new javax.swing.JLabel();
        NumeroComprovante = new javax.swing.JLabel();
        TipoComprovante = new javax.swing.JLabel();
        Proveedor = new javax.swing.JLabel();
        text_Id = new javax.swing.JTextField();
        text_Fecha = new javax.swing.JTextField();
        Text_nemeroComprovante = new javax.swing.JTextField();
        text_TipoComprovante = new javax.swing.JTextField();
        text_Proveedor = new javax.swing.JTextField();
        BT_Guardar = new javax.swing.JButton();
        BT_Cancelar = new javax.swing.JButton();
        BT_OK = new javax.swing.JButton();
        Editar_tabla = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BT_Salir.setText("SALIR");
        BT_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_SalirActionPerformed(evt);
            }
        });
        getContentPane().add(BT_Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, -1, -1));

        titulo.setFont(new java.awt.Font("Times New Roman", 2, 48)); // NOI18N
        titulo.setText("CABECERA COMPRA");
        getContentPane().add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));

        icono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/sillaa.png"))); // NOI18N
        getContentPane().add(icono, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, -1, -1));

        Id.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        Id.setText("Id: ");
        getContentPane().add(Id, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, -1, -1));

        Fecha.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        Fecha.setText("Fecha: ");
        getContentPane().add(Fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, -1, -1));

        NumeroComprovante.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        NumeroComprovante.setText("Numero Comprovante: ");
        getContentPane().add(NumeroComprovante, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, -1, -1));

        TipoComprovante.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        TipoComprovante.setText("Tipo Comprovante: ");
        getContentPane().add(TipoComprovante, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 370, -1, -1));

        Proveedor.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        Proveedor.setText("Proveedor: ");
        getContentPane().add(Proveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 400, -1, -1));
        getContentPane().add(text_Id, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, 220, -1));
        getContentPane().add(text_Fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, 220, -1));

        Text_nemeroComprovante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Text_nemeroComprovanteActionPerformed(evt);
            }
        });
        getContentPane().add(Text_nemeroComprovante, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 340, 220, -1));
        getContentPane().add(text_TipoComprovante, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 370, 220, -1));
        getContentPane().add(text_Proveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 400, 220, -1));

        BT_Guardar.setText("Guardar");
        getContentPane().add(BT_Guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 300, 80, -1));

        BT_Cancelar.setText("Cancelar");
        BT_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_CancelarActionPerformed(evt);
            }
        });
        getContentPane().add(BT_Cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 330, 80, -1));

        BT_OK.setText("OK");
        getContentPane().add(BT_OK, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 360, 80, -1));

        Editar_tabla.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Información: ");
        Editar_tabla.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jButton1.setText("Editar");
        Editar_tabla.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, -1, -1));

        jButton2.setText("Eliminar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        Editar_tabla.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, -1, -1));

        jLabel2.setText("Buscar: ");
        Editar_tabla.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, -1, -1));
        Editar_tabla.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, 190, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        Editar_tabla.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 440, 70));

        getContentPane().add(Editar_tabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, 520, 140));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/FondoAzul.png"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BT_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_SalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_BT_SalirActionPerformed

    private void Text_nemeroComprovanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Text_nemeroComprovanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Text_nemeroComprovanteActionPerformed

    private void BT_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_CancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BT_CancelarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cabecera_Compra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cabecera_Compra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cabecera_Compra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cabecera_Compra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cabecera_Compra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BT_Cancelar;
    private javax.swing.JButton BT_Guardar;
    private javax.swing.JButton BT_OK;
    private javax.swing.JButton BT_Salir;
    private javax.swing.JPanel Editar_tabla;
    private javax.swing.JLabel Fecha;
    private javax.swing.JLabel Id;
    private javax.swing.JLabel NumeroComprovante;
    private javax.swing.JLabel Proveedor;
    private javax.swing.JTextField Text_nemeroComprovante;
    private javax.swing.JLabel TipoComprovante;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel icono;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField text_Fecha;
    private javax.swing.JTextField text_Id;
    private javax.swing.JTextField text_Proveedor;
    private javax.swing.JTextField text_TipoComprovante;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
