/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

/**
 *
 * @author roni9
 */
public class Cabecera_Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Cabecera_Ventana
     */
    public Cabecera_Ventana() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BT_Salir = new javax.swing.JButton();
        titulo = new javax.swing.JLabel();
        Icono = new javax.swing.JLabel();
        Id = new javax.swing.JLabel();
        Fecha = new javax.swing.JLabel();
        Numero_comprobante = new javax.swing.JLabel();
        Tipo_comprovante = new javax.swing.JLabel();
        Cliente = new javax.swing.JLabel();
        text_Id = new javax.swing.JTextField();
        text_Fecha = new javax.swing.JTextField();
        text_numeroComprovante = new javax.swing.JTextField();
        text_tipo_Comprovante = new javax.swing.JTextField();
        text_cliente = new javax.swing.JTextField();
        BT_Guardar = new javax.swing.JButton();
        BT_Cancelar = new javax.swing.JButton();
        BT_OK = new javax.swing.JButton();
        Editar_tabla = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BT_Salir.setText("SALIR");
        BT_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_SalirActionPerformed(evt);
            }
        });
        getContentPane().add(BT_Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 10, -1, -1));

        titulo.setBackground(new java.awt.Color(255, 255, 255));
        titulo.setFont(new java.awt.Font("Times New Roman", 2, 48)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 255, 255));
        titulo.setText("CABECERA VENTANA");
        getContentPane().add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, -1));

        Icono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/silla2.png"))); // NOI18N
        getContentPane().add(Icono, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, -1, -1));

        Id.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Id.setText("Id: ");
        getContentPane().add(Id, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, -1, -1));

        Fecha.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Fecha.setText("Fecha: ");
        getContentPane().add(Fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, -1, -1));

        Numero_comprobante.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Numero_comprobante.setText("Numero Comprovante: ");
        getContentPane().add(Numero_comprobante, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, -1, -1));

        Tipo_comprovante.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Tipo_comprovante.setText("Tipo Comprovante: ");
        getContentPane().add(Tipo_comprovante, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, -1, -1));

        Cliente.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Cliente.setText("Cliente: ");
        getContentPane().add(Cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 390, -1, -1));
        getContentPane().add(text_Id, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 240, -1));

        text_Fecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_FechaActionPerformed(evt);
            }
        });
        getContentPane().add(text_Fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, 240, -1));
        getContentPane().add(text_numeroComprovante, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, 240, -1));
        getContentPane().add(text_tipo_Comprovante, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 350, 240, -1));
        getContentPane().add(text_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 390, 240, -1));

        BT_Guardar.setText("Guardar");
        getContentPane().add(BT_Guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 260, 80, -1));

        BT_Cancelar.setText("Cancelar");
        getContentPane().add(BT_Cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 300, 80, -1));

        BT_OK.setText("OK");
        getContentPane().add(BT_OK, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 340, 80, -1));

        jLabel1.setText("Información: ");

        jButton1.setText("Editar");

        jButton2.setText("Eliminar");

        jLabel2.setText("Buscar: ");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 497, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 63, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout Editar_tablaLayout = new javax.swing.GroupLayout(Editar_tabla);
        Editar_tabla.setLayout(Editar_tablaLayout);
        Editar_tablaLayout.setHorizontalGroup(
            Editar_tablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Editar_tablaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Editar_tablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Editar_tablaLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        Editar_tablaLayout.setVerticalGroup(
            Editar_tablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Editar_tablaLayout.createSequentialGroup()
                .addGroup(Editar_tablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Editar_tablaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(Editar_tablaLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(Editar_tablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2)
                            .addComponent(jLabel2)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        getContentPane().add(Editar_tabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, 570, 130));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/FondoAzul.png"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BT_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_SalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_BT_SalirActionPerformed

    private void text_FechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_FechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_FechaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cabecera_Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cabecera_Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cabecera_Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cabecera_Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cabecera_Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BT_Cancelar;
    private javax.swing.JButton BT_Guardar;
    private javax.swing.JButton BT_OK;
    private javax.swing.JButton BT_Salir;
    private javax.swing.JLabel Cliente;
    private javax.swing.JPanel Editar_tabla;
    private javax.swing.JLabel Fecha;
    private javax.swing.JLabel Icono;
    private javax.swing.JLabel Id;
    private javax.swing.JLabel Numero_comprobante;
    private javax.swing.JLabel Tipo_comprovante;
    private javax.swing.JLabel fondo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField text_Fecha;
    private javax.swing.JTextField text_Id;
    private javax.swing.JTextField text_cliente;
    private javax.swing.JTextField text_numeroComprovante;
    private javax.swing.JTextField text_tipo_Comprovante;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
