/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

/**
 *
 * @author roni9
 */
public class VProveedor extends javax.swing.JFrame {

    /**
     * Creates new form VProveedor
     */
    public VProveedor() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BT_Salir = new javax.swing.JButton();
        titulo = new javax.swing.JLabel();
        icono = new javax.swing.JLabel();
        Identificacion = new javax.swing.JLabel();
        texte_identificacion = new javax.swing.JTextField();
        tipo_identificacion = new javax.swing.JLabel();
        text_tipo_identificacion = new javax.swing.JTextField();
        nombre_comercial = new javax.swing.JLabel();
        texte_nombre_Comercial = new javax.swing.JTextField();
        representante = new javax.swing.JLabel();
        text_representante = new javax.swing.JTextField();
        BT_grabar = new javax.swing.JButton();
        BT_Cancelar = new javax.swing.JButton();
        BT_ok = new javax.swing.JButton();
        editar_tabla = new javax.swing.JPanel();
        informacion = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BT_Salir.setText("SALIR");
        BT_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_SalirActionPerformed(evt);
            }
        });
        getContentPane().add(BT_Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 10, -1, -1));

        titulo.setFont(new java.awt.Font("Times New Roman", 2, 48)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 255, 255));
        titulo.setText("PROVEEDOR");
        getContentPane().add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, -1, -1));

        icono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/provedor.jpeg"))); // NOI18N
        getContentPane().add(icono, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, -1, -1));

        Identificacion.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Identificacion.setText("Identificación: ");
        getContentPane().add(Identificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, -1, 20));

        texte_identificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texte_identificacionActionPerformed(evt);
            }
        });
        getContentPane().add(texte_identificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, 230, -1));

        tipo_identificacion.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tipo_identificacion.setText("Tipo de Identificación:");
        getContentPane().add(tipo_identificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, -1));
        getContentPane().add(text_tipo_identificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, 230, -1));

        nombre_comercial.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        nombre_comercial.setText("Nombre Comercial:");
        getContentPane().add(nombre_comercial, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, -1, -1));
        getContentPane().add(texte_nombre_Comercial, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, 230, -1));

        representante.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        representante.setText("Representante:");
        getContentPane().add(representante, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, -1, -1));
        getContentPane().add(text_representante, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 340, 230, -1));

        BT_grabar.setText("Grabar");
        getContentPane().add(BT_grabar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 240, 80, -1));

        BT_Cancelar.setText("Cancelar");
        getContentPane().add(BT_Cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 280, 80, -1));

        BT_ok.setText("OK");
        getContentPane().add(BT_ok, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 320, 80, -1));

        informacion.setText("Información:");

        jButton1.setText("Editar");

        jButton2.setText("Eliminar");

        jLabel1.setText("Buscar:");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 484, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 103, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout editar_tablaLayout = new javax.swing.GroupLayout(editar_tabla);
        editar_tabla.setLayout(editar_tablaLayout);
        editar_tablaLayout.setHorizontalGroup(
            editar_tablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editar_tablaLayout.createSequentialGroup()
                .addGroup(editar_tablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(editar_tablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(editar_tablaLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(informacion, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(editar_tablaLayout.createSequentialGroup()
                            .addGap(67, 67, 67)
                            .addComponent(jButton1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jButton2)
                            .addGap(44, 44, 44)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        editar_tablaLayout.setVerticalGroup(
            editar_tablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editar_tablaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(informacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editar_tablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        getContentPane().add(editar_tabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 560, 180));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/FondoAzul.png"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BT_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_SalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_BT_SalirActionPerformed

    private void texte_identificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texte_identificacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texte_identificacionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VProveedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BT_Cancelar;
    private javax.swing.JButton BT_Salir;
    private javax.swing.JButton BT_grabar;
    private javax.swing.JButton BT_ok;
    private javax.swing.JLabel Identificacion;
    private javax.swing.JPanel editar_tabla;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel icono;
    private javax.swing.JLabel informacion;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel nombre_comercial;
    private javax.swing.JLabel representante;
    private javax.swing.JTextField text_representante;
    private javax.swing.JTextField text_tipo_identificacion;
    private javax.swing.JTextField texte_identificacion;
    private javax.swing.JTextField texte_nombre_Comercial;
    private javax.swing.JLabel tipo_identificacion;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
