/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import DataBase.ComboBox;
import Objetos.*;

/**
 *
 * @author Personal
 */
public class VUsuario extends javax.swing.JFrame {

    /**
     * Creates new form VUsuario
     */
    public VUsuario() {
        initComponents();
        this.setLocationRelativeTo(null);
        cargarCombos();
    }
    public  void cargarCombos(){
       cbRol.removeAllItems();
       ComboBox cbx= new ComboBox();
       cbx.cbRol(cbRol);
               
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BotonSalir = new javax.swing.JButton();
        Usuario1 = new javax.swing.JLabel();
        nombre_Usuario = new javax.swing.JLabel();
        Apellido_Usuario = new javax.swing.JLabel();
        Contraseña_Usuario = new javax.swing.JLabel();
        Correo = new javax.swing.JLabel();
        Direccion_Usuario = new javax.swing.JLabel();
        Celular_Usuario = new javax.swing.JLabel();
        text_nombre = new javax.swing.JTextField();
        texte_apellido = new javax.swing.JTextField();
        text_Correo = new javax.swing.JTextField();
        text_Direccion = new javax.swing.JTextField();
        text_Contraseña = new javax.swing.JPasswordField();
        text_Celular = new javax.swing.JTextField();
        Rol = new javax.swing.JLabel();
        Buscar_tabla = new javax.swing.JPanel();
        informacion = new javax.swing.JLabel();
        BT_Editar = new javax.swing.JButton();
        BT_Eliminar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        grabar = new javax.swing.JButton();
        Cancelar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cbRol = new javax.swing.JComboBox<>();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 255, 102));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BotonSalir.setText("SALIR");
        BotonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSalirActionPerformed(evt);
            }
        });
        getContentPane().add(BotonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 10, -1, -1));

        Usuario1.setFont(new java.awt.Font("Times New Roman", 2, 48)); // NOI18N
        Usuario1.setForeground(new java.awt.Color(255, 255, 255));
        Usuario1.setText("USUARIOS");
        getContentPane().add(Usuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, -1, 40));

        nombre_Usuario.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        nombre_Usuario.setText("Nombre:");
        getContentPane().add(nombre_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, -1, -1));

        Apellido_Usuario.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Apellido_Usuario.setText("Apellido: ");
        getContentPane().add(Apellido_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, -1, -1));

        Contraseña_Usuario.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Contraseña_Usuario.setText("Contraseña: ");
        getContentPane().add(Contraseña_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 100, -1, -1));

        Correo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Correo.setText("Correo: ");
        getContentPane().add(Correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, -1, -1));

        Direccion_Usuario.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Direccion_Usuario.setText("Dirección:");
        getContentPane().add(Direccion_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 160, -1, -1));

        Celular_Usuario.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Celular_Usuario.setText("Núm. Celular: ");
        getContentPane().add(Celular_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 230, -1, -1));
        getContentPane().add(text_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 230, -1));
        getContentPane().add(texte_apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 230, -1));
        getContentPane().add(text_Correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, 230, -1));
        getContentPane().add(text_Direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 160, 180, -1));
        getContentPane().add(text_Contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 100, 180, -1));
        getContentPane().add(text_Celular, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 230, 180, -1));

        Rol.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Rol.setText("Rol:");
        getContentPane().add(Rol, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 290, -1, -1));

        informacion.setText("Información:");

        BT_Editar.setText("Editar");
        BT_Editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_EditarActionPerformed(evt);
            }
        });

        BT_Eliminar.setText("Eliminar");

        jLabel1.setText("Buscar:");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 553, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 86, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout Buscar_tablaLayout = new javax.swing.GroupLayout(Buscar_tabla);
        Buscar_tabla.setLayout(Buscar_tablaLayout);
        Buscar_tablaLayout.setHorizontalGroup(
            Buscar_tablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Buscar_tablaLayout.createSequentialGroup()
                .addGroup(Buscar_tablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Buscar_tablaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(informacion, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Buscar_tablaLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(Buscar_tablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(Buscar_tablaLayout.createSequentialGroup()
                                .addComponent(BT_Editar)
                                .addGap(18, 18, 18)
                                .addComponent(BT_Eliminar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        Buscar_tablaLayout.setVerticalGroup(
            Buscar_tablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Buscar_tablaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(informacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Buscar_tablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BT_Editar)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BT_Eliminar))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        getContentPane().add(Buscar_tabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, 650, 180));

        grabar.setText("Grabar");
        getContentPane().add(grabar, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 340, -1, -1));

        Cancelar.setText("Cancelar");
        getContentPane().add(Cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 340, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Registro:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, -1, -1));

        getContentPane().add(cbRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 290, 170, -1));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/FondoAzul.png"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-7, -4, 800, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_BotonSalirActionPerformed

    private void BT_EditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_EditarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BT_EditarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Apellido_Usuario;
    private javax.swing.JButton BT_Editar;
    private javax.swing.JButton BT_Eliminar;
    private javax.swing.JButton BotonSalir;
    private javax.swing.JPanel Buscar_tabla;
    private javax.swing.JButton Cancelar;
    private javax.swing.JLabel Celular_Usuario;
    private javax.swing.JLabel Contraseña_Usuario;
    private javax.swing.JLabel Correo;
    private javax.swing.JLabel Direccion_Usuario;
    private javax.swing.JLabel Rol;
    private javax.swing.JLabel Usuario1;
    private javax.swing.JComboBox<Rol> cbRol;
    private javax.swing.JLabel fondo;
    private javax.swing.JButton grabar;
    private javax.swing.JLabel informacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel nombre_Usuario;
    private javax.swing.JTextField text_Celular;
    private javax.swing.JPasswordField text_Contraseña;
    private javax.swing.JTextField text_Correo;
    private javax.swing.JTextField text_Direccion;
    private javax.swing.JTextField text_nombre;
    private javax.swing.JTextField texte_apellido;
    // End of variables declaration//GEN-END:variables
}
